// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type RegisterDto = {
    /**
     * 用户邮箱
     */
    email: string;
    /**
     * 密码（8-128 个字符）
     */
    password: string;
};

export type AuthUserResponse = {
    /**
     * 用户 ID
     */
    id: string;
    /**
     * 用户邮箱
     */
    email: string;
    /**
     * 用户状态
     */
    status: string;
    /**
     * 注册时间
     */
    createdAt: string;
};

export type AuthResponse = {
    /**
     * JWT access token
     */
    accessToken: string;
    /**
     * 当前用户信息
     */
    user: AuthUserResponse;
};

export type LoginDto = {
    /**
     * 用户邮箱
     */
    email: string;
    /**
     * 密码
     */
    password: string;
};

export type HealthControllerCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthControllerCheckResponses = {
    200: unknown;
};

export type ReadyzControllerCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type ReadyzControllerCheckResponses = {
    200: unknown;
};

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthControllerRegisterErrors = {
    /**
     * 邮箱已注册
     */
    409: unknown;
    /**
     * 请求过于频繁
     */
    429: unknown;
};

export type AuthControllerRegisterResponses = {
    /**
     * 注册成功
     */
    201: AuthResponse;
};

export type AuthControllerRegisterResponse = AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginErrors = {
    /**
     * 邮箱或密码错误
     */
    401: unknown;
    /**
     * 请求过于频繁
     */
    429: unknown;
};

export type AuthControllerLoginResponses = {
    /**
     * 登录成功
     */
    200: AuthResponse;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshErrors = {
    /**
     * refresh token 无效或已过期
     */
    401: unknown;
    /**
     * 请求过于频繁
     */
    429: unknown;
};

export type AuthControllerRefreshResponses = {
    /**
     * 刷新成功
     */
    200: AuthResponse;
};

export type AuthControllerRefreshResponse = AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutResponses = {
    /**
     * 已退出
     */
    200: unknown;
};

export type AuthControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthControllerMeErrors = {
    /**
     * 未认证
     */
    401: unknown;
};

export type AuthControllerMeResponses = {
    /**
     * 当前用户信息
     */
    200: AuthUserResponse;
};

export type AuthControllerMeResponse = AuthControllerMeResponses[keyof AuthControllerMeResponses];
