// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type RegisterDto = {
    /**
     * 用户邮箱
     */
    email: string;
    /**
     * 密码（8-128 个字符）
     */
    password: string;
};

export type AuthUserResponse = {
    /**
     * 用户 ID
     */
    id: string;
    /**
     * 用户邮箱
     */
    email: string;
    /**
     * 用户状态
     */
    status: string;
    /**
     * 注册时间
     */
    createdAt: string;
};

export type AuthResponse = {
    /**
     * JWT access token
     */
    accessToken: string;
    /**
     * 当前用户信息
     */
    user: AuthUserResponse;
};

export type LoginDto = {
    /**
     * 用户邮箱
     */
    email: string;
    /**
     * 密码
     */
    password: string;
};

export type CreateKbDto = {
    /**
     * KB 名称（1-200 个字符）
     */
    name: string;
    /**
     * KB 描述（最多 500 个字符）
     */
    description?: string;
};

export type KbResponse = {
    /**
     * KB ID
     */
    id: string;
    /**
     * KB 名称
     */
    name: string;
    /**
     * KB 描述
     */
    description?: string;
    /**
     * 创建时间
     */
    createdAt: string;
    /**
     * 更新时间
     */
    updatedAt: string;
};

export type KbListResponse = {
    /**
     * KB 列表
     */
    items: Array<KbResponse>;
};

export type PresignUploadDto = {
    /**
     * 目标 KB ID
     */
    kbId: string;
    /**
     * 文件名
     */
    fileName: string;
    /**
     * MIME 类型
     */
    mimeType: string;
    /**
     * 文件大小（字节）
     */
    sizeBytes: number;
};

export type PresignUploadResponse = {
    /**
     * 上传 URL
     */
    uploadUrl: string;
    /**
     * HTTP 方法
     */
    uploadMethod: string;
    /**
     * 对象存储 key
     */
    objectKey: string;
    /**
     * 签名过期时间
     */
    expiresAt: string;
    /**
     * 创建 Document 所需 token
     */
    uploadToken: string;
};

export type CreateDocumentDto = {
    /**
     * 目标 KB ID
     */
    kbId: string;
    /**
     * 对象存储 key
     */
    objectKey: string;
    /**
     * 上传签名 token
     */
    uploadToken: string;
    /**
     * 原始文件名
     */
    originalName: string;
    /**
     * MIME 类型
     */
    mimeType?: string;
    /**
     * 文件大小（字节）
     */
    sizeBytes?: number;
};

export type DocumentResponse = {
    /**
     * Document ID
     */
    id: string;
    /**
     * 所属 KB ID
     */
    kbId: string;
    /**
     * 来源类型
     */
    sourceType: string;
    /**
     * 原始文件名
     */
    originalName: string;
    /**
     * 处理状态
     */
    status: string;
    /**
     * 错误码
     */
    errorCode?: string | null;
    /**
     * 错误信息
     */
    errorMessage?: string | null;
    /**
     * 创建时间
     */
    createdAt: string;
    /**
     * 更新时间
     */
    updatedAt: string;
};

export type DocumentListResponse = {
    /**
     * Document 列表
     */
    items: Array<DocumentResponse>;
};

export type ChunkResponse = {
    /**
     * Chunk ID
     */
    id: string;
    /**
     * 所属 Document ID
     */
    documentId: string;
    /**
     * 所属 KB ID
     */
    kbId: string;
    /**
     * 来源类型
     */
    sourceType: string;
    /**
     * 文本内容
     */
    content: string;
    /**
     * 标题路径
     */
    headingPath: Array<string>;
    /**
     * 定位锚点
     */
    anchor: string;
    /**
     * token 数量
     */
    tokenCount: number;
    /**
     * 元数据
     */
    metadata: {
        [key: string]: unknown;
    };
    /**
     * 创建时间
     */
    createdAt: string;
};

export type ChunkListResponse = {
    /**
     * Chunk 列表
     */
    items: Array<ChunkResponse>;
    /**
     * 下一页 cursor
     */
    nextCursor?: string | null;
};

export type ChatRequestDto = {
    /**
     * 用户消息内容
     */
    message: string;
    /**
     * 会话 ID，不传则创建新会话
     */
    conversationId?: string;
    /**
     * 客户端消息 ID，用于幂等去重
     */
    clientMessageId?: string;
};

export type ChatErrorResponse = {
    /**
     * 错误状态码
     */
    statusCode: number;
    /**
     * 错误信息
     */
    message: string;
    /**
     * 错误码
     */
    error?: string | null;
};

export type ConversationResponse = {
    /**
     * 会话 ID
     */
    id: string;
    /**
     * KB ID
     */
    kbId: string;
    /**
     * 会话标题
     */
    title?: string | null;
    /**
     * 创建时间
     */
    createdAt: string;
    /**
     * 更新时间
     */
    updatedAt: string;
};

export type ConversationListResponse = {
    /**
     * 会话列表
     */
    items: Array<ConversationResponse>;
};

export type CitationResponse = {
    /**
     * citation ID
     */
    id: string;
    /**
     * chunk ID
     */
    chunkId: string;
    /**
     * 文档 ID
     */
    documentId: string;
    /**
     * 来源类型
     */
    sourceType: string;
    /**
     * 引用排序
     */
    order: number;
    /**
     * 相关性分数
     */
    score: number;
    /**
     * chunk 文本预览
     */
    chunkText: string;
    /**
     * 标题路径
     */
    headingPath: Array<string>;
    /**
     * chunk 锚点
     */
    anchor?: string | null;
    /**
     * 页码
     */
    page?: number | null;
    /**
     * 边界框坐标
     */
    bbox?: {
        [key: string]: unknown;
    } | null;
};

export type MessageResponse = {
    /**
     * 消息 ID
     */
    id: string;
    /**
     * 会话 ID
     */
    conversationId: string;
    /**
     * 角色
     */
    role: string;
    /**
     * 消息内容
     */
    content?: string | null;
    /**
     * 消息状态
     */
    status: string;
    /**
     * provider 名称
     */
    provider?: string | null;
    /**
     * 模型名称
     */
    model?: string | null;
    /**
     * 错误码
     */
    errorCode?: string | null;
    /**
     * 错误信息（脱敏）
     */
    errorMessage?: string | null;
    /**
     * 创建时间
     */
    createdAt: string;
    /**
     * assistant 消息的 citations
     */
    citations?: Array<CitationResponse>;
};

export type ConversationDetailResponse = {
    /**
     * 会话 ID
     */
    id: string;
    /**
     * KB ID
     */
    kbId: string;
    /**
     * 会话标题
     */
    title?: string | null;
    /**
     * 创建时间
     */
    createdAt: string;
    /**
     * 更新时间
     */
    updatedAt: string;
    /**
     * 会话消息列表
     */
    messages: Array<MessageResponse>;
};

export type HealthControllerCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthControllerCheckResponses = {
    200: unknown;
};

export type ReadyzControllerCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type ReadyzControllerCheckResponses = {
    200: unknown;
};

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthControllerRegisterErrors = {
    /**
     * 邮箱已注册
     */
    409: unknown;
    /**
     * 请求过于频繁
     */
    429: unknown;
};

export type AuthControllerRegisterResponses = {
    /**
     * 注册成功
     */
    201: AuthResponse;
};

export type AuthControllerRegisterResponse = AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginErrors = {
    /**
     * 邮箱或密码错误
     */
    401: unknown;
    /**
     * 请求过于频繁
     */
    429: unknown;
};

export type AuthControllerLoginResponses = {
    /**
     * 登录成功
     */
    200: AuthResponse;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshErrors = {
    /**
     * refresh token 无效或已过期
     */
    401: unknown;
    /**
     * 请求过于频繁
     */
    429: unknown;
};

export type AuthControllerRefreshResponses = {
    /**
     * 刷新成功
     */
    200: AuthResponse;
};

export type AuthControllerRefreshResponse = AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutResponses = {
    /**
     * 已退出
     */
    200: unknown;
};

export type AuthControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthControllerMeErrors = {
    /**
     * 未认证
     */
    401: unknown;
};

export type AuthControllerMeResponses = {
    /**
     * 当前用户信息
     */
    200: AuthUserResponse;
};

export type AuthControllerMeResponse = AuthControllerMeResponses[keyof AuthControllerMeResponses];

export type KnowledgeBaseControllerListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/kbs';
};

export type KnowledgeBaseControllerListErrors = {
    /**
     * 未认证
     */
    401: unknown;
};

export type KnowledgeBaseControllerListResponses = {
    /**
     * 个人 KB 列表（按 updatedAt desc, id desc 排序）
     */
    200: KbListResponse;
};

export type KnowledgeBaseControllerListResponse = KnowledgeBaseControllerListResponses[keyof KnowledgeBaseControllerListResponses];

export type KnowledgeBaseControllerCreateData = {
    body: CreateKbDto;
    path?: never;
    query?: never;
    url: '/kbs';
};

export type KnowledgeBaseControllerCreateErrors = {
    /**
     * 输入校验失败（含传入 spaceId 被拒绝的场景）
     */
    400: unknown;
    /**
     * 未认证
     */
    401: unknown;
};

export type KnowledgeBaseControllerCreateResponses = {
    /**
     * KB 创建成功
     */
    201: KbResponse;
};

export type KnowledgeBaseControllerCreateResponse = KnowledgeBaseControllerCreateResponses[keyof KnowledgeBaseControllerCreateResponses];

export type KnowledgeBaseControllerDetailData = {
    body?: never;
    path: {
        /**
         * KB ID
         */
        id: string;
    };
    query?: never;
    url: '/kbs/{id}';
};

export type KnowledgeBaseControllerDetailErrors = {
    /**
     * 未认证
     */
    401: unknown;
    /**
     * KB 不存在或无权访问
     */
    404: unknown;
};

export type KnowledgeBaseControllerDetailResponses = {
    /**
     * KB 详情
     */
    200: KbResponse;
};

export type KnowledgeBaseControllerDetailResponse = KnowledgeBaseControllerDetailResponses[keyof KnowledgeBaseControllerDetailResponses];

export type UploadsControllerPresignData = {
    body: PresignUploadDto;
    path?: never;
    query?: never;
    url: '/uploads/presign';
};

export type UploadsControllerPresignErrors = {
    /**
     * 校验失败
     */
    400: unknown;
    /**
     * 未认证
     */
    401: unknown;
    /**
     * KB 不存在或无权访问
     */
    404: unknown;
};

export type UploadsControllerPresignResponses = {
    /**
     * 上传初始化成功，返回直传 URL
     */
    201: PresignUploadResponse;
};

export type UploadsControllerPresignResponse = UploadsControllerPresignResponses[keyof UploadsControllerPresignResponses];

export type DocumentsControllerCreateData = {
    body: CreateDocumentDto;
    path?: never;
    query?: never;
    url: '/documents';
};

export type DocumentsControllerCreateErrors = {
    /**
     * 校验失败
     */
    400: unknown;
    /**
     * 未认证
     */
    401: unknown;
    /**
     * KB 不存在或无权访问
     */
    404: unknown;
};

export type DocumentsControllerCreateResponses = {
    /**
     * Document 创建成功并入队
     */
    201: DocumentResponse;
};

export type DocumentsControllerCreateResponse = DocumentsControllerCreateResponses[keyof DocumentsControllerCreateResponses];

export type DocumentsControllerDetailData = {
    body?: never;
    path: {
        /**
         * Document ID
         */
        id: string;
    };
    query?: never;
    url: '/documents/{id}';
};

export type DocumentsControllerDetailErrors = {
    /**
     * 未认证
     */
    401: unknown;
    /**
     * Document 不存在或无权访问
     */
    404: unknown;
};

export type DocumentsControllerDetailResponses = {
    /**
     * Document 详情
     */
    200: DocumentResponse;
};

export type DocumentsControllerDetailResponse = DocumentsControllerDetailResponses[keyof DocumentsControllerDetailResponses];

export type DocumentsControllerListByKbData = {
    body?: never;
    path: {
        /**
         * KB ID
         */
        kbId: string;
    };
    query?: never;
    url: '/kbs/{kbId}/documents';
};

export type DocumentsControllerListByKbErrors = {
    /**
     * 未认证
     */
    401: unknown;
    /**
     * KB 不存在或无权访问
     */
    404: unknown;
};

export type DocumentsControllerListByKbResponses = {
    /**
     * Document 列表
     */
    200: DocumentListResponse;
};

export type DocumentsControllerListByKbResponse = DocumentsControllerListByKbResponses[keyof DocumentsControllerListByKbResponses];

export type DocumentsControllerGetChunksData = {
    body?: never;
    path: {
        /**
         * Document ID
         */
        id: string;
    };
    query?: {
        /**
         * 每页数量，默认 100，最大 500
         */
        limit?: string;
        /**
         * 分页 cursor
         */
        cursor?: string;
    };
    url: '/documents/{id}/chunks';
};

export type DocumentsControllerGetChunksErrors = {
    /**
     * 未认证
     */
    401: unknown;
    /**
     * Document 不存在或无权访问
     */
    404: unknown;
};

export type DocumentsControllerGetChunksResponses = {
    /**
     * Chunk 列表
     */
    200: ChunkListResponse;
};

export type DocumentsControllerGetChunksResponse = DocumentsControllerGetChunksResponses[keyof DocumentsControllerGetChunksResponses];

export type ChatControllerChatData = {
    body: ChatRequestDto;
    path: {
        /**
         * KB ID
         */
        kbId: string;
    };
    query?: never;
    url: '/kbs/{kbId}/chat';
};

export type ChatControllerChatErrors = {
    /**
     * 输入校验失败
     */
    400: ChatErrorResponse;
    /**
     * 未认证
     */
    401: ChatErrorResponse;
    /**
     * KB 或会话不存在/无权访问
     */
    404: ChatErrorResponse;
};

export type ChatControllerChatError = ChatControllerChatErrors[keyof ChatControllerChatErrors];

export type ChatControllerChatResponses = {
    /**
     * 流式回答（text/event-stream）
     */
    200: unknown;
};

export type ChatControllerListConversationsData = {
    body?: never;
    path: {
        /**
         * KB ID
         */
        kbId: string;
    };
    query?: never;
    url: '/kbs/{kbId}/conversations';
};

export type ChatControllerListConversationsErrors = {
    /**
     * 未认证
     */
    401: ChatErrorResponse;
    /**
     * KB 不存在或无权访问
     */
    404: ChatErrorResponse;
};

export type ChatControllerListConversationsError = ChatControllerListConversationsErrors[keyof ChatControllerListConversationsErrors];

export type ChatControllerListConversationsResponses = {
    /**
     * 会话列表
     */
    200: ConversationListResponse;
};

export type ChatControllerListConversationsResponse = ChatControllerListConversationsResponses[keyof ChatControllerListConversationsResponses];

export type ChatControllerGetConversationData = {
    body?: never;
    path: {
        /**
         * KB ID
         */
        kbId: string;
        /**
         * 会话 ID
         */
        conversationId: string;
    };
    query?: never;
    url: '/kbs/{kbId}/conversations/{conversationId}';
};

export type ChatControllerGetConversationErrors = {
    /**
     * 未认证
     */
    401: ChatErrorResponse;
    /**
     * 会话不存在或无权访问
     */
    404: ChatErrorResponse;
};

export type ChatControllerGetConversationError = ChatControllerGetConversationErrors[keyof ChatControllerGetConversationErrors];

export type ChatControllerGetConversationResponses = {
    /**
     * 会话详情
     */
    200: ConversationDetailResponse;
};

export type ChatControllerGetConversationResponse = ChatControllerGetConversationResponses[keyof ChatControllerGetConversationResponses];
